# Generated by Django 4.1.13 on 2024-04-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='category',
            new_name='exercise_type',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='ExerciseCategory',
        ),
    ]
