# Generated by Django 4.1.13 on 2024-04-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_exercise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
