# Generated by Django 4.1.13 on 2024-04-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_cardioworkoutinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardioworkoutinstance',
            name='average_heart_rate',
            field=models.IntegerField(blank=True, help_text='Average heart rate (bpm)', null=True),
        ),
        migrations.AlterField(
            model_name='cardioworkoutinstance',
            name='distance',
            field=models.FloatField(blank=True, help_text='Distance in miles', null=True),
        ),
        migrations.AlterField(
            model_name='cardioworkoutinstance',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the workout', null=True),
        ),
    ]
