# Generated by Django 4.1.13 on 2024-04-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_strengthtraininginstance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StrengthTrainingInstance',
        ),
    ]
