# Generated by Django 4.1.13 on 2024-04-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_strengthworkoutinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strengthworkoutinstance',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strengthworkoutinstance',
            name='weight',
            field=models.FloatField(blank=True, help_text='(lbs)', null=True),
        ),
    ]
