# Generated by Django 4.1.13 on 2024-04-29 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
